# Generated by Django 2.0.5 on 2018-05-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('MAN_CODE', models.AutoField(primary_key=True, serialize=False)),
                ('MAN_COMPANY', models.CharField(max_length=30)),
                ('MAN_STREET', models.CharField(max_length=30)),
                ('MAN_CITY', models.CharField(max_length=30)),
                ('MAN_STATE', models.CharField(max_length=30)),
                ('MAN_ZIP', models.IntegerField(max_length=5)),
                ('MAN_AREACODE', models.IntegerField(max_length=3)),
                ('MAN_PHONE', models.IntegerField(max_length=7)),
                ('MAN_ACCNUM', models.IntegerField(max_length=16)),
            ],
        ),
    ]
