# Generated by Django 2.0.5 on 2018-05-23 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwservices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('BRAND_ID', models.AutoField(primary_key=True, serialize=False)),
                ('BRAND_NAME', models.CharField(max_length=30)),
                ('BRAND_LEVEL', models.CharField(max_length=30)),
                ('MAN_CODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hwservices.Manufacturer')),
            ],
        ),
    ]
