# Generated by Django 2.0.5 on 2018-05-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwservices', '0004_auto_20180523_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='BRAND_LEVEL',
            field=models.CharField(choices=[('premium', 'premium'), ('mid-level', 'mid-level'), ('entry-level', 'entry-level')], max_length=30),
        ),
    ]
