# Generated by Django 2.0.5 on 2018-05-24 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwservices', '0005_auto_20180524_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='MAN_ACCNUM',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(16), django.core.validators.MinLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='MAN_AREACODE',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(3), django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='MAN_ZIP',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(5), django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='model',
            name='MODEL_HP',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='model',
            name='MODEL_HWRP',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='model',
            name='MODEL_JETS',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='model',
            name='MODEL_MOTORS',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='model',
            name='MODEL_SEATCAP',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='model',
            name='MODEL_SRP',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='model',
            name='MODEL_WATCAP',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='model',
            name='MODEL_WEIGTH',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.DecimalValidator]),
        ),
    ]
