# Generated by Django 2.0.5 on 2018-05-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwservices', '0006_auto_20180524_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='MAN_ACCNUM',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='MAN_AREACODE',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='MAN_ZIP',
            field=models.IntegerField(),
        ),
    ]
