# Generated by Django 2.0.5 on 2018-05-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwservices', '0007_auto_20180524_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='MAN_ACCNUM',
            field=models.CharField(max_length=16),
        ),
    ]
