# Generated by Django 2.0.5 on 2018-05-28 22:45

from django.db import migrations, models
import hwservices.models


class Migration(migrations.Migration):

    dependencies = [
        ('hwservices', '0008_auto_20180528_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='MAN_ZIP',
            field=models.IntegerField(validators=[hwservices.models.validate_integer]),
        ),
    ]
